### ISSUE TITLE
Dependencies to MechEngineer and CustomComponents

### ISSUE THREAD

**Issue by mad2342** [BattletechModders/ExpandedInitiative#2]
Hi IceRaptor,
Wanted to try this mod for a mostly vanilla game, was hold back by the mentioned deps stated in mod,json.
Looked at the code a bit and didn't see anything on first glance..
Is it possible to use this for an otherwise unmodded game?
Best regards, Mad

**Comment by mad2342** [comment]
Ok, mod.json on Github already lost the deps, but in the .zip of the release they're in. fyi

**Comment by IceRaptor** [comment]
@mad2342 sorry about that, those dependencies aren't actually necessary. You can play without them. I've uploaded a new 0.2.1 zip with an updated mod.json, and you can freely strip out those dependencies in your copy. You still need the IRBTModUtils dependency, though.

Cheers!
